<?php

/*
 * Branding configs for your application
 */
return [
    'login' => [
        'page_title' => 'Masuk',
        'headline' => 'Masuk',
        'subheadline' => 'Masuk ke akun anda dibawah',
        'show_subheadline' => false,
        'email_address' => 'Email',
        'password' => 'Kata Sandi',
        'remember_me' => 'Ingat Saya',
        'edit' => 'Ubah',
        'button' => 'Lanjutkan',
        'forget_password' => 'Lupa Kata Sandi?',
        'dont_have_an_account' => 'Belum punya akun?',
        'sign_up' => 'Daftar',
        'social_auth_authenticated_message' => 'Anda berhasil masuk via __social_providers_list__. Please login to that network below.',
        'change_email' => 'Ubah Email',
        'couldnt_find_your_account' => 'Tidak bisa menemukan akun anda',
    ],
    'register' => [
        'page_title' => 'Daftar',
        'headline' => 'Daftar',
        'subheadline' => 'Daftar sebagai pengguna dibawah ini.',
        'show_subheadline' => false,
        'name' => 'Nama',
        'email_address' => 'Email Aktif',
        'password' => 'Kata Sandi',
        'password_confirmation' => 'Konfirmasi Kata sandi',
        'already_have_an_account' => 'Sudah punya akun?',
        'sign_in' => 'Masuk',
        'button' => 'Lanjutkan',
        'email_registration_disabled' => 'Registrasi dikunci. Gunakan akun sosial Media login.',
    ],
    'verify' => [
        'page_title' => 'Verify Your Account',
        'headline' => 'Verify your email address',
        'subheadline' => 'Before you can proceed you must verify your email.',
        'show_subheadline' => false,
        'description' => 'Before proceeding, please check your email for a verification link. If you did not receive the email,',
        'new_request_link' => 'click here to request another',
        'new_link_sent' => 'A new link has been sent to your email address.',
        'or' => 'Or',
        'logout' => 'click here to logout',
    ],
    'passwordConfirm' => [
        'page_title' => 'Confirm Your Password',
        'headline' => 'Confirm Password',
        'subheadline' => 'Be sure to confirm your password below',
        'show_subheadline' => false,
        'password' => 'Password',
        'button' => 'Confirm password',
    ],
    'passwordResetRequest' => [
        'page_title' => 'Request a Password Reset',
        'headline' => 'Reset password',
        'subheadline' => 'Enter your email below to reset your password',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'button' => 'Send password reset link',
        'or' => 'or',
        'return_to_login' => 'return to login',
    ],
    'passwordReset' => [
        'page_title' => 'Reset Your Password',
        'headline' => 'Reset Password',
        'subheadline' => 'Reset your password below',
        'show_subheadline' => false,
        'email' => 'Email Address',
        'password' => 'Password',
        'password_confirm' => 'Confirm Password',
        'button' => 'Reset Password',
    ],
    'twoFactorChallenge' => [
        'page_title' => 'Two Factor Challenge',
        'headline_auth' => 'Authentication Code',
        'subheadline_auth' => 'Enter the authentication code provided by your authenticator application.',
        'show_subheadline_auth' => false,
        'headline_recovery' => 'Recovery Code',
        'subheadline_recovery' => 'Please confirm access to your account by entering one of your emergency recovery codes.',
        'show_subheadline_recovery' => false,
    ],

];
